### ISSUE TITLE
Criar formulário que lista todos os animais cadastrados e da a opção de editar

### ISSUE THREAD

**Issue by chalkmaster** [chalkmaster/VetMaxPitagoras#15]
Igual feito no tutorial da aula: unidade 2 encontro 4

**Comment by DanielaIzabel** [comment]
Criada a tela de cadastro, entidade, interface para o repository, criado o repository,  e funcionalidade para incluir um animal e listar os animais cadastrados. Ainda resta organizar a tela (tarefa em aberto), adaptar para que ao remover um animal do dataGridView o mesmo seja removido do respository também, e criar validação dos campos do formulário.

**Comment by DanielaIzabel** [comment]
Finalizado.
