### ISSUE TITLE
ajustar layout das telas

### ISSUE THREAD

**Issue by chalkmaster** [chalkmaster/VetMaxPitagoras#20]

**Comment by engeziellithon** [comment]
Djavan olha como eu fiz o cadastro de usuário só olhar no as propriedades,pq quando a janela de cadastro de animal e redimensionada seu formulário não fica no centro da página.Pra min fica um pouco estranho.Pode melhorar o cadastro de animal se achar que deve.
Tem várias formas 
https://stackoverflow.com/questions/10599961/align-controls-to-center-in-a-flowlayout

**Comment by lucianoromualdo** [comment]
Foi feito o ajuste e alinhamento de todas as telas
