### ISSUE TITLE
Verificar as validação formulário de cadastro de animal 

### ISSUE THREAD

**Issue by engeziellithon** [chalkmaster/VetMaxPitagoras#25]
Não permitir que antes do login acessar o cadastro de animal.

**Comment by engeziellithon** [comment]
Alguns validação foram criadas por min, mas enum especies e raça vão ser criados e essas validações vão ter que sofrer alterações.

**Comment by Clever25** [comment]
Não entendi bem, vou pegar  outra inssue e  conversamos sobre essa depois novamente

**Comment by engeziellithon** [comment]
eu fiz algumas validações no cadastro de animal se está vazio não deixa cadastrar por exemplo ,mas vários campos lá precisam ser criados ai depois você criaria essas outras validações,mas se quiser pega outra fique á vontade,faça outra que não depende de ninguém pra ficar pronta.
