### ISSUE TITLE
Resolver no problema cadastro de animal - Duplicando 

### ISSUE THREAD

**Issue by engeziellithon** [chalkmaster/VetMaxPitagoras#73]
Quando é feito o cadastro de um animal pela primeira vez funciona normalmente,mas ao tenta cadastrar pelo segundo fez o registro fica duplicado.

**Comment by DanielaIzabel** [comment]
Este problema já estava resolvido antes, com o problema que houve no projeto a parte da correção não foi recuperada, vou apenas copiar do comit e recolocar no código...

**Comment by DanielaIzabel** [comment]
Finalizado.
