### ISSUE TITLE
Verificar tela de cadastro de animal 

### ISSUE THREAD

**Issue by alexleonardo1** [chalkmaster/VetMaxPitagoras#76]
*Falta incluir o comando  "LIMPAR" e "VOLTAR" após o preenchimento do formulário de cadastro.
*Retirar o comando "SAIR".
*A tela abaixo dos campos de cadastro de animal possui um menu onde o mesmo contém campos que estão um sobrepondo aos outros, também é necessário que corrijam os erros ortográficos tais como acentuação e Çdilha.
* Colocar os campos "Nome do animal" "Nome do dono" e "Telefone" como campos obrigatórios, (Incluir um ASTERISCO antes do nome do campo).

**Comment by engeziellithon** [comment]
1) A tela abaixo dos campos de cadastro de animal possui um menu onde o mesmo contém campos que estão um sobrepondo aos outros
R: tem um issue aberta sobre isto. https://github.com/chalkmaster/VetMaxPitagoras/issues/71

2) *Falta incluir o comando "LIMPAR" e "VOLTAR" após o preenchimento do formulário de cadastro.
Pode fazer 2 issues uma de Excluir selecionado e outra de excluir todos.O voltar vai ter que fazer depois que o login estiver pronto.

3) Colocar os campos "Nome do animal" "Nome do dono" e "Telefone" como campos obrigatórios, (Incluir um ASTERISCO antes do nome do campo).
boa ideia,telefone é um campo desnecessário no cadastro de animal,pois uma animal não tem telefone.
tem issue relacionada a isso tb deviam ser fazer isso também https://github.com/chalkmaster/VetMaxPitagoras/issues/57
mas para ficar mais fácil criei outra só para ser feito isso.

**Comment by kampfull** [comment]
animalForms não esta abrindo, tentei realizar algumas alterações mas no final não obtive sucesso, o ideal seria criar outro formulário do zero, a diversos erros no atual.
